---
# apt-install the AIDE IDS on the server

  - name: Install all those dependencies
    apt: pkg={{item}} state=present
    with_items:
      - aide
      - aide-common
    tags:
      - install

  - name: set where the reports are emailed
    lineinfile:
      dest: /etc/default/aide
      regexp: '^MAILTO'
      line: "MAILTO={{ email_to }}"
      state: present
    tags:
      - install

  - name: Do not send an email if nothing has changed
    lineinfile:
      dest: /etc/default/aide
      regexp: '^QUIETREPORTS'
      line: "QUIETREPORTS={{ quiet_reports }}"
      state: present
    tags:
      - install

  - name: Just do the sha256 checksum or it takes forever
    lineinfile: 
      dest=/etc/aide/aide.conf 
      regexp="^Checksums" 
      line="Checksums = {{ checksums }}" 
      state=present
    tags:
      - install

  - name: change up aide.conf to standards set in aide_ignore_list
    lineinfile:
      dest: /etc/aide/aide.conf
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
      state: present
    with_items: aide_ignore_list
    tags:
      - install

  - name:  Add crontab to reset DB nightly
    cron:
      user="root"
      name="Redo Aide DB nightly"
      hour=23
      minute=45
      job="/usr/sbin/aideinit -y -f"
    tags:
      - install

    notify:
      - init aide database
